/*********************************
CREATE VIEW INDICACOR SINTÈTIC
*********************************/
CREATE OR REPLACE VIEW ORIGEN.EILU2019_INDSINT_QUALITAT AS 
SELECT DISTINCT 
DB.IDENT,grau_mast,
TRBPRN1.DS_VALOR TRBPRN1,
JORNADA.IND_VALOR_NORM_QUALIT JORNADA,JORNADA.DS_VALOR DS_JORNADA,
TR_SUELDO.IND_VALOR_NORM_QUALIT TR_SUELDO,TR_SUELDO.DS_VALOR DS_SUELDO,
SIT_PRO.IND_VALOR_NORM_QUALIT SIT_PRO,SIT_PRO.DS_VALOR DS_SIT_PRO,
TR_D19.IND_VALOR_NORM_QUALIT TR_D19,TR_D19.DS_VALOR DS_TR_D19,
TR_D20.IND_VALOR_NORM_QUALIT TR_D20,TR_D20.DS_VALOR DS_TR_20,
TR_D21.IND_VALOR_NORM_QUALIT TR_D21,TR_D21.DS_VALOR DS_TR_D21,
HATR_E11.IND_VALOR_NORM_QUALIT HATR_E11,HATR_E11.DS_VALOR DS_HATR_11,
TRABOC.IND_VALOR_NORM_QUALIT TRABOC,TRABOC.DS_VALOR DS_TRABOC,
HATR_TIEMP.IND_VALOR_NORM_QUALIT HATR_TIEMP,HATR_TIEMP.DS_VALOR DS_HATR_TIEMP,
HATR_E27.IND_VALOR_NORM_QUALIT HATR_E27,HATR_E27.DS_VALOR DS_HATR_E27,
INCRM_SOU,
-----------------------------------
 -- Indicador sintètic
    ROUND((
        NVL(JORNADA.IND_VALOR_NORM_QUALIT, 0) +
        NVL(TR_SUELDO.IND_VALOR_NORM_QUALIT, 0) +
        NVL(SIT_PRO.IND_VALOR_NORM_QUALIT, 0) +
        NVL(TR_D19.IND_VALOR_NORM_QUALIT, 0) +
        NVL(TR_D20.IND_VALOR_NORM_QUALIT, 0) +
        NVL(TR_D21.IND_VALOR_NORM_QUALIT, 0) +
        NVL(HATR_E11.IND_VALOR_NORM_QUALIT, 0) +
        NVL(TRABOC.IND_VALOR_NORM_QUALIT, 0) +
        NVL(HATR_TIEMP.IND_VALOR_NORM_QUALIT, 0) +
        NVL(HATR_E27.IND_VALOR_NORM_QUALIT, 0)
    ) / 10, 3) AS INDICADOR_SINTETIC
FROM ORIGEN.EILU2019_DATASET DB,
/************************************/
-- 'TRBPRN1' , 'JORNADA' , 'TR_SUELDO' , 'SIT_PRO' , 'TR_D19' , 'TR_D20' , 'TR_D21' , 'HATR_E11' , 'TRABOC' , 'HATR_TIEMP', 'HATR_E27'
-----------------------------------
--Situación laboral actual
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM 
ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='TRBPRN1') TRBPRN1,
----------------------------------
--Jornada actual
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM 
ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='JORNADA') JORNADA,
----------------------------------
--Sueldo mensual neto actual
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM 
ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='TR_SUELDO') TR_SUELDO,
----------------------------------
--Situación profesional actual
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM 
ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='SIT_PRO') SIT_PRO,
----------------------------------
--Nivel de formación más apropiado para realizar el trabajo actual
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM 
ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='TR_D19') TR_D19,
----------------------------------
--Área de estudio más apropiada para el trabajo actual
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM 
ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='TR_D20') TR_D20,
----------------------------------
-- Se hace uso en el trabajo actual de los conocimientos y habilidades adquiridos en estos estudios
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM 
ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='TR_D21') TR_D21,
----------------------------------
--Tiempo transcurrido desde que finalizó estos estudios hasta que empezó a trabajar
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM 
ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='HATR_E11') HATR_E11,
----------------------------------
--Ocupación que desempeña en el puesto de trabajo actual
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM 
ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='TRABOC') TRABOC,
----------------------------------
--Tiempo que ha estado trabajando desde que terminó los estudios
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM 
ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='HATR_TIEMP') HATR_TIEMP,
----------------------------------
--Cree que el título universitario le ha servido para encontrar trabajo
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM 
ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='HATR_E27') HATR_E27
/**************************************/
WHERE 
/*CAMP*/ DB.TRBPRN1=TRBPRN1.ID_VALOR(+) and
/*CAMP*/ DB.JORNADA=JORNADA.ID_VALOR(+) and
/*CAMP*/ DB.TR_SUELDO=TR_SUELDO.ID_VALOR(+) and
/*CAMP*/ DB.SIT_PRO=SIT_PRO.ID_VALOR(+) and
/*CAMP*/ DB.TR_D19=TR_D19.ID_VALOR(+) and
/*CAMP*/ DB.TR_D20=TR_D20.ID_VALOR(+) and
/*CAMP*/ DB.TR_D21=TR_D21.ID_VALOR(+) and
/*CAMP*/ DB.HATR_E11=HATR_E11.ID_VALOR(+) and
/*CAMP*/ DB.TRABOC=TRABOC.ID_VALOR(+) and
/*CAMP*/ DB.HATR_TIEMP=HATR_TIEMP.ID_VALOR(+) and
/*CAMP*/ DB.HATR_E27=HATR_E27.ID_VALOR(+)
---------------------------
AND DB.TRBPRN1 IN ('1','2') -- PER TREBALLAR (Actiu, Desempleado)
;



-----------------------------------
--Situación laboral actual
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM 
ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='TRBPRN1');
----------------------------------
--Jornada actual
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM 
ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='JORNADA');
----------------------------------
--Sueldo mensual neto actual
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM 
ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='TR_SUELDO');
----------------------------------
--Situación profesional actual
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM 
ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='SIT_PRO');
----------------------------------
--Nivel de formación más apropiado para realizar el trabajo actual
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM 
ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='TR_D19');
----------------------------------
--Área de estudio más apropiada para el trabajo actual
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM 
ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='TR_D20');
----------------------------------
-- Se hace uso en el trabajo actual de los conocimientos y habilidades adquiridos en estos estudios
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM 
ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='TR_D21');
----------------------------------
--Tiempo transcurrido desde que finalizó estos estudios hasta que empezó a trabajar
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM 
ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='HATR_E11');
----------------------------------
--Ocupación que desempeña en el puesto de trabajo actual
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM 
ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='TRABOC');
----------------------------------
--Tiempo que ha estado trabajando desde que terminó los estudios
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM 
ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='HATR_TIEMP');
----------------------------------
--Cree que el título universitario le ha servido para encontrar trabajo
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM 
ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='HATR_E27');