/************************
CSV'S
*************************/
-- GENERALS GRADUATS RSPECTE SITUACIO LABORAL PER RAMA

SELECT  
DISTINCT DB.RAMA,T.DS_VALOR,
COUNT(IDENT) GRADUATS,
COUNT(DECODE(DB.TRBPRN1,1,1,NULL)) GRADUATS_TREBALLANT,
COUNT(DECODE(DB.TRBPRN1,2,1,NULL)) GRADUATS_DESEMPLEO,
COUNT(DECODE(DB.TRBPRN1,3,1,NULL)) GRADUATS_INACTIUS,
COUNT(DECODE(DB.TRBPRN1,NULL,1)) GRADUATS_NA,
DECODE (DB.SEXO,'1', 'Home', '2', 'Dona','NA') SEXE
FROM ORIGEN.EILU2019_DATASET DB,
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='TRBPRN1') TR,
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='RAMA') T
-----------
WHERE 1=1
AND DB.TRBPRN1 = TR.ID_VALOR(+)
AND /*CAMP*/ DB.RAMA=T.ID_VALOR(+)
GROUP BY  DB.RAMA,T.DS_VALOR,DECODE (DB.SEXO,'1', 'Home', '2', 'Dona','NA') 
ORDER BY T.DS_VALOR;



-- HA MARXAT A L'ETRANGER DESPRÉS DE GRADUAR-SE
SELECT 
--DB.IDENT,grau_mast,
--DB.SEXO,DB.EDAD,NACIO,
---------------------------------
T.IND_VALOR_NORM_QUALIT T,T.DS_VALOR,
------ 
COUNT(*) PERSONES
FROM ORIGEN.EILU2019_DATASET DB,
----------------------------------
--LLOC DE RESIDÈNCIA
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='LUG_RES_PAIS') T
-----------------------------------
WHERE 1=1 AND
/*CAMP*/ DB.LUG_RES_PAIS=T.ID_VALOR(+)
GROUP BY 
--DB.SEXO,DB.EDAD,DB.NACIO,
---------------------------------
T.IND_VALOR_NORM_QUALIT,T.DS_VALOR
------ 
;

/************************************
GRADUATS PER SEXE I RAMES
*************************************/
SELECT DB.RAMA,DB.SEXO,grau_mast,
--DB.IDENT,
---------------------------------
T.DS_VALOR,
------ 
COUNT(*) PERSONES
FROM ORIGEN.EILU2019_DATASET DB,
----------------------------------
--Tiempo que ha estado trabajando desde que terminó los estudios
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='RAMA') T
-----------------------------------
WHERE 1=1 AND
/*CAMP*/ DB.RAMA=T.ID_VALOR(+)
GROUP BY 
DB.SEXO,DB.RAMA,grau_mast,
---------------------------------
T.DS_VALOR
------ 
ORDER BY grau_mast,db.rama
;

/************************************
GRADUATS PER SEXE i ambit estudi
*************************************/
SELECT grau_mast,
--DB.IDENT,
---------------------------------
T.DS_VALOR,
------ 
COUNT(CASE WHEN DB.SEXO=1 THEN IDENT END) HOMES,
COUNT(CASE WHEN DB.SEXO=2 THEN IDENT END) DONES
FROM ORIGEN.EILU2019_DATASET DB,
----------------------------------
--Tiempo que ha estado trabajando desde que terminó los estudios
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='AMBITO') T
-----------------------------------
WHERE 1=1 AND
/*CAMP*/ DB.AMBITO=T.ID_VALOR(+)
GROUP BY 
grau_mast,
---------------------------------
T.DS_VALOR
------ 
ORDER BY T.DS_VALOR,grau_mast
;
/************************************
GRADUATS PER sou i ambit estudi
*************************************/
SELECT TT.DS_VALOR TITUL,' ' CAMP_BUIT,TT.DS_VALOR,
T.IND_VALOR_MARCA_CLASSE,
--TRUNC(AVG(T.IND_VALOR_MARCA_CLASSE)) SOU,
---------------------------------
TR.DS_VALOR RAMA,grau_mast,count(*) GRADUATS
----
FROM ORIGEN.EILU2019_DATASET DB,
----------------------------------
--Sou
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='TR_SUELDO') T,
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='RAMA') Tr,
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='TITU') Tt
-----------------------------------
WHERE 1=1 AND
/*CAMP*/ DB.TR_SUELDO=T.ID_VALOR(+) AND
/*CAMP*/ DB.RAMA=TR.ID_VALOR(+) AND
/*CAMP*/ DB.TITU=TT.ID_VALOR(+)
GROUP BY TR.DS_VALOR,grau_mast,T.IND_VALOR_MARCA_CLASSE,TT.DS_VALOR
ORDER BY TT.DS_VALOR, 1,3
;

/************************************
INDICADOR QUALITAT per Alum, sexe i rama
************************************/

SELECT 
'ALUM-'||DB.IDENT ALUM,' ' CAMP_BUIT, Q.INDICADOR_SINTETIC IND_QUALITAT, 
DECODE (DB.SEXO,'1', 'Home', '2', 'Dona','NA') SEXE,
TR.DS_VALOR RAMA
FROM 
 ORIGEN.EILU2019_DATASET_10000 DB,
 ORIGEN.EILU2019_INDSINT_QUALITAT Q,
 (SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='RAMA') Tr
WHERE 1=1
--PK----------------------------
AND DB.IDENT = Q.IDENT
AND DB.GRAU_MAST = Q.GRAU_MAST
--------------------------------
/*CAMP*/ AND DB.RAMA=TR.ID_VALOR(+);

/******************************
SURVEY
******************************/
SELECT 
'ALUM-'||DB.IDENT ALUM, 1 count_AL, Q.INDICADOR_SINTETIC IND_QUALITAT, 
 DECODE (DB.SEXO,'1', 'Home', '2', 'Dona','N/A') Sexe,
 NVL(JORNADA.DS_VALOR,'N/A') Jornada,
 NVL(EDAD.DS_VALOR,'N/A') Edat,
 NVL(RAMA.DS_VALOR,'N/A') Rama,NVL(PR_SUELDO.DS_VALOR,'N/A') Sou_inicial,NVL(TR_SUELDO.DS_VALOR,'N/A') Sou_actual,
 NVL(DB.INCRM_SOU,'N/A') Increment_de_sou,NVL(LUG_RES_PAIS.DS_VALOR,'N/A') Pais_que_marxa,NVL(EST_M1.DS_VALOR,'N/A') Erasmus_SN,
 NVL(HATR_E11.DS_VALOR,'N/A') TEMPS_TRIGAT_TROBAR_FEINA, NVL(HATR_E27.DS_VALOR,'N/A') TITOL_UTIL_FEINA,
 CASE WHEN Q.INDICADOR_SINTETIC>=0.7 THEN 'INSERCIO_BONA'
      WHEN Q.INDICADOR_SINTETIC>0.4 AND Q.INDICADOR_SINTETIC<0.7 THEN 'INSERCIO_ADEQUADA'
      WHEN Q.INDICADOR_SINTETIC<=0.4 THEN 'INSERCIO_DOLENTA'
      WHEN DB.TRBPRN1 IN ('3') THEN 'INACTIU' END QUALITAT_INSERCIO
FROM 
 ORIGEN.EILU2019_DATASET_10000 DB,
 ORIGEN.EILU2019_INDSINT_QUALITAT Q,
 (SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='JORNADA') JORNADA,
 (SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='EDAD') EDAD,
 (SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='RAMA') RAMA,
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='TR_SUELDO') TR_SUELDO,
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='PR_SUELDO') PR_SUELDO,
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='LUG_RES_PAIS') LUG_RES_PAIS,
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='EST_M1') EST_M1,
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='HATR_E11') HATR_E11,
(SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='HATR_E27') HATR_E27
WHERE 1=1
--PK----------------------------
AND DB.IDENT = Q.IDENT
AND DB.GRAU_MAST = Q.GRAU_MAST
--------------------------------
/*CAMP*/ AND DB.JORNADA=JORNADA.ID_VALOR(+)
/*CAMP*/ AND DB.EDAD=EDAD.ID_VALOR(+)
/*CAMP*/ AND DB.RAMA=RAMA.ID_VALOR(+)
/*CAMP*/ AND DB.TR_SUELDO=TR_SUELDO.ID_VALOR(+)
/*CAMP*/ AND DB.PR_SUELDO=PR_SUELDO.ID_VALOR(+)
/*CAMP*/ AND DB.LUG_RES_PAIS=LUG_RES_PAIS.ID_VALOR(+)
/*CAMP*/ AND DB.EST_M1=EST_M1.ID_VALOR(+)
/*CAMP*/ AND DB.HATR_E11=HATR_E11.ID_VALOR(+)
/*CAMP*/ AND DB.HATR_E27=HATR_E27.ID_VALOR(+)
;

/************************************
INDICADOR QUALITAT promig per rames i sexe
************************************/

SELECT 
TRUNC(Q.INDICADOR_SINTETIC,2) IND_QUALITAT,
COUNT(*) graduats,
DECODE (DB.SEXO,'1', 'Home', '2', 'Dona','NA') SEXE,
TR.DS_VALOR RAMA
-----------------
FROM 
 ORIGEN.EILU2019_DATASET_10000 DB,
 ORIGEN.EILU2019_INDSINT_QUALITAT Q,
 (SELECT DISTINCT
C.AMBIT,C.ID_CAMP,C.TAULA,C.DS_CAMP,
V.TAULA,V.ID_VALOR,V.DS_VALOR,V.IND_VALOR_MARCA_CLASSE,V.IND_VALOR_NORM_QUALIT
FROM ORIGEN.EILU2019_CAMPS C, ORIGEN.EILU2019_TAULES_DS V
WHERE C.TAULA=V.TAULA
AND C.ID_CAMP='RAMA') Tr
WHERE 1=1
--PK----------------------------
AND DB.IDENT = Q.IDENT
AND DB.GRAU_MAST = Q.GRAU_MAST
--------------------------------
/*CAMP*/ AND DB.RAMA=TR.ID_VALOR(+)
group by TRUNC(Q.INDICADOR_SINTETIC,2),
DECODE (DB.SEXO,'1', 'Home', '2', 'Dona','NA'),
TR.DS_VALOR
order by 1
;
/************************************
INDICADOR QUALITAT per variables
************************************/

----------------------------
SELECT 
    Q.IND_QUALITAT Serie_INDEX_QUALITAT,
    Q.graduats AS Graduats_Qualitat,
    Q_JORNADA.graduats AS Graduats_Jornada,
    Q_TR_SUELDO.graduats AS Graduats_Sueldo,
    Q_SIT_PRO.graduats AS Graduats_Sit_Pro,
    Q_TR_D19.graduats AS Graduats_D19,
    Q_TR_D20.graduats AS Graduats_D20,
    Q_TR_D21.graduats AS Graduats_D21,
    Q_HATR_E11.graduats AS Graduats_HATR_E11,
    Q_TRABOC.graduats AS Graduats_TRABOC,
    Q_HATR_TIEMP.graduats AS Graduats_HATR_TIEMP,
    Q_HATR_E27.graduats AS Graduats_HATR_E27
FROM 
    (SELECT TRUNC(INDICADOR_SINTETIC, 2) AS IND_QUALITAT, COUNT(*) AS graduats 
     FROM ORIGEN.EILU2019_INDSINT_QUALITAT_T 
     GROUP BY TRUNC(INDICADOR_SINTETIC, 2)) Q
LEFT JOIN 
    (SELECT TRUNC(JORNADA, 2) AS IND_QUALITAT, COUNT(*) AS graduats 
     FROM ORIGEN.EILU2019_INDSINT_QUALITAT_T
     GROUP BY TRUNC(JORNADA, 2)) Q_JORNADA
ON Q.IND_QUALITAT = Q_JORNADA.IND_QUALITAT
LEFT JOIN 
    (SELECT TRUNC(TR_SUELDO, 2) AS IND_QUALITAT, COUNT(*) AS graduats 
     FROM ORIGEN.EILU2019_INDSINT_QUALITAT_T
     GROUP BY TRUNC(TR_SUELDO, 2)) Q_TR_SUELDO
ON Q.IND_QUALITAT = Q_TR_SUELDO.IND_QUALITAT
LEFT JOIN 
    (SELECT TRUNC(SIT_PRO, 2) AS IND_QUALITAT, COUNT(*) AS graduats 
     FROM ORIGEN.EILU2019_INDSINT_QUALITAT_T
     GROUP BY TRUNC(SIT_PRO, 2)) Q_SIT_PRO
ON Q.IND_QUALITAT = Q_SIT_PRO.IND_QUALITAT
LEFT JOIN 
    (SELECT TRUNC(TR_D19, 2) AS IND_QUALITAT, COUNT(*) AS graduats 
     FROM ORIGEN.EILU2019_INDSINT_QUALITAT_T
     GROUP BY TRUNC(TR_D19, 2)) Q_TR_D19
ON Q.IND_QUALITAT = Q_TR_D19.IND_QUALITAT
LEFT JOIN 
    (SELECT TRUNC(TR_D20, 2) AS IND_QUALITAT, COUNT(*) AS graduats 
     FROM ORIGEN.EILU2019_INDSINT_QUALITAT_T
     GROUP BY TRUNC(TR_D20, 2)) Q_TR_D20
ON Q.IND_QUALITAT = Q_TR_D20.IND_QUALITAT
LEFT JOIN 
    (SELECT TRUNC(TR_D21, 2) AS IND_QUALITAT, COUNT(*) AS graduats 
     FROM ORIGEN.EILU2019_INDSINT_QUALITAT_T
     GROUP BY TRUNC(TR_D21, 2)) Q_TR_D21
ON Q.IND_QUALITAT = Q_TR_D21.IND_QUALITAT
LEFT JOIN
     (select TRUNC(HATR_E11,2) IND_QUALITAT,COUNT(*) graduats from  ORIGEN.EILU2019_INDSINT_QUALITAT_T group by TRUNC(HATR_E11,2)) Q_HATR_E11
ON Q.IND_QUALITAT = Q_HATR_E11.IND_QUALITAT
LEFT JOIN
     (select TRUNC(TRABOC,2) IND_QUALITAT,COUNT(*) graduats from  ORIGEN.EILU2019_INDSINT_QUALITAT_T group by TRUNC(TRABOC,2)) Q_TRABOC
ON Q.IND_QUALITAT = Q_TRABOC.IND_QUALITAT
LEFT JOIN
     (select TRUNC(HATR_TIEMP,2) IND_QUALITAT,COUNT(*) graduats from  ORIGEN.EILU2019_INDSINT_QUALITAT_T group by TRUNC(HATR_TIEMP,2)) Q_HATR_TIEMP
ON Q.IND_QUALITAT = Q_HATR_TIEMP.IND_QUALITAT
LEFT JOIN
     (select TRUNC(HATR_E27,2) IND_QUALITAT,COUNT(*) graduats from  ORIGEN.EILU2019_INDSINT_QUALITAT_T group by TRUNC(HATR_E27,2)) Q_HATR_E27
ON Q.IND_QUALITAT = Q_HATR_E27.IND_QUALITAT
ORDER BY 1;


--'TRBPRN1' , 'JORNADA' , 'TR_SUELDO' , 'SIT_PRO' , 'TR_D19' , 'TR_D20' , 'TR_D21' , 'HATR_E11' , 'TRABOC' , 'HATR_TIEMP', 'HATR_E27'