/*************************
ACTIUS 40.429 (43.134 TOTAL)
**************************/
SELECT  
DISTINCT COUNT(IDENT)
FROM ORIGEN.EILU2019_DATASET DB
WHERE DB.TRBPRN1 IN ('1','2') -- PER TREBALLAR
;

--0,7% QUE TENEN ns/nc

/**********************
Increment SOU
***********************/
SELECT 
    DB.IDENT,
    DB.SEXO,
    DB.EDAD,
    DB.TR_SUELDO,
    DB.PR_SUELDO,
    TR.DS_VALOR AS TR_DS_VALOR,
    PR.DS_VALOR AS PR_DS_VALOR,
    NVL(TR.IND_VALOR_MARCA_CLASSE, 0) AS SOU_ACT,
    NVL(PR.IND_VALOR_MARCA_CLASSE, 0) AS SOU_INI,
    CASE 
        WHEN NVL(TR.IND_VALOR_MARCA_CLASSE, 0) = 0 AND NVL(PR.IND_VALOR_MARCA_CLASSE, 0) = 0 THEN NULL
        WHEN NVL(TR.IND_VALOR_MARCA_CLASSE, 0) > NVL(PR.IND_VALOR_MARCA_CLASSE, 0) THEN 'Incrementa'
        WHEN NVL(TR.IND_VALOR_MARCA_CLASSE, 0) < NVL(PR.IND_VALOR_MARCA_CLASSE, 0) THEN 'Baixa'
        ELSE 'Igual'
    END AS INCRM_SOU_CALC,
    DB.INCRM_SOU 
FROM ORIGEN.EILU2019_DATASET DB
LEFT JOIN (SELECT * FROM ORIGEN.EILU2019_TAULES_DS WHERE TAULA = 'TSUELDO') TR 
    ON DB.TR_SUELDO = TR.ID_VALOR
LEFT JOIN (SELECT * FROM ORIGEN.EILU2019_TAULES_DS WHERE TAULA = 'TSUELDO') PR 
    ON DB.PR_SUELDO = PR.ID_VALOR;

-------------------------------------------------
MERGE INTO ORIGEN.EILU2019_DATASET DB
USING (
    SELECT 
        DB.IDENT,
        DB.GRAU_MAST,
        CASE 
            WHEN NVL(TR.IND_VALOR_MARCA_CLASSE, 0) = 0 AND NVL(PR.IND_VALOR_MARCA_CLASSE, 0) = 0 THEN NULL
            WHEN NVL(TR.IND_VALOR_MARCA_CLASSE, 0) > NVL(PR.IND_VALOR_MARCA_CLASSE, 0) THEN 'Incrementa'
            WHEN NVL(TR.IND_VALOR_MARCA_CLASSE, 0) < NVL(PR.IND_VALOR_MARCA_CLASSE, 0) THEN 'Baixa'
            ELSE 'Igual'
        END AS INCRM_SOU
    FROM ORIGEN.EILU2019_DATASET DB
    LEFT JOIN (SELECT * FROM ORIGEN.EILU2019_TAULES_DS WHERE TAULA = 'TSUELDO') TR 
        ON DB.TR_SUELDO = TR.ID_VALOR
    LEFT JOIN (SELECT * FROM ORIGEN.EILU2019_TAULES_DS WHERE TAULA = 'TSUELDO') PR 
        ON DB.PR_SUELDO = PR.ID_VALOR
) CALC ON (DB.IDENT = CALC.IDENT AND DB.GRAU_MAST = CALC.GRAU_MAST)
WHEN MATCHED THEN
    UPDATE SET DB.INCRM_SOU = CALC.INCRM_SOU;
---------------------------------------------
